name: packages
description: "Build CLI, agent image, init package and example packages"

inputs:
  init-package:
    description: 'Build the init package'
    required: false
    default: 'true'
  build-examples:
    description: 'Build the example packages'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - run: |
        make build-ui-linux-amd ARCH=amd64
      shell: bash
    - run: |
        make retrieve-packages ARCH=amd64
      shell: bash
