name: node-cache
description: "Node cache"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 18
        cache: "npm"
        cache-dependency-path: "src/ui/package-lock.json"
