name: node-cache
description: "Node cache"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version: 18
        cache: "npm"
        cache-dependency-path: "src/ui/package-lock.json"
