name: node-cache
description: "Node cache"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
      with:
        node-version: 18
        cache: "npm"
        cache-dependency-path: "src/ui/package-lock.json"
