name: Publish Zarf UI on Tag

permissions:
  contents: read

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the repo and setup the tooling for this job
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Setup NodeJS
        uses: ./.github/actions/node

      - name: Setup K3d
        uses: ./.github/actions/k3d

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Build binary and zarf packages
        uses: ./.github/actions/packages

      - name: Cache browsers
        uses: actions/cache@v3
        with:
          path: "~/.cache/ms-playwright/"
          key: ${{ runner.os }}-browsers

      - name: Ensure playright is installed
        run: npx --prefix src/ui playwright install

      - name: Run UI tests
        run: make test-ui

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs

      - name: Save playright logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: src/ui/playwright-report/
          retention-days: 30

      # After we run the tests we need to aggressively cleanup files to reduce disk pressure
      - name: Cleanup files
        uses: ./.github/actions/cleanup-files

      - name: Setup the CLI version
        run: |
          echo ZARF_CLI_VERSION=$(cat go.mod | grep "github.com/defenseunicorns/zarf " | cut -d " " -f 2) >> $GITHUB_ENV

      # Create the GitHub release notes, and publish built artifacts
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}

      - name: Save CVE report
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: cve-report
          path: build/zarf-ui-known-cves.csv
