name: Validate API Schema
on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Docs and schemas
        run: "make test-api-schema"

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
